name: Build 
on:
  pull_request:
    branches: [development, master]   
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  

      - name: Restore dependencies         
	run: dotnet restore src/back-end/TaskApp.Api/TaskApp.Api.csproj


      - name: Build project
        run: dotnet build src/back-end/TaskApp.Api/TaskApp.Api.csproj --no-restore --configuration Release

