name: Unit Tests Service

on:
  pull_request:
    branches: [development, master] 

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore src/back-end/TaskApp.Api/TaskApp.Api.Tests.csproj

      - name: Build
        run: dotnet build src/back-end/TaskApp.Api/TaskApp.Api.Tests.csproj --no-restore --configuration Release

      - name: Run tests
        run: dotnet test src/back-end/TaskApp.Api/TaskApp.Api.Tests.csproj --no-build --configuration Release --logger "trx"
